name: 'bundle-size'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build && node bundle-size.js > baseline.json
      - run: node bundle-size.js
