name: 'bundle-size'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: 'commit message'
        id: 'commit_message'
        run: echo "::set-output name=msg::$(git log -1 --pretty=%B)"
      - name: 'Fail on skip ci'
        if: contains(steps.commit_message.outputs.msg, 'skip ci')
        run: exit 1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - if: github.event_name == 'pull_request'
        run: aws s3 cp s3://educative-build-sizes/${{github.event.pull_request.base.sha}}.json baseline.json && yarn && yarn build && node bundle-size.js
        working-directory: src/../
      - if: github.event_name == 'push'
        run: echo "Started" && yarn && yarn build && node bundle-size.js > baseline.json && aws s3 cp baseline.json s3://educative-build-sizes/${{github.sha}}.json
        working-directory: src/../
