name: 'bundle-size'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      - run: yarn && yarn build && echo "Done" && node bundle-size.js && echo "Done Again"
